### ISSUE TITLE
pyotherside doesn't compile with gcc 13.2

### ISSUE THREAD

**Issue by jmlich** [thp/pyotherside#128]
I am trying to compile pyotherside with gcc 13.2 agains qt6.

The build script is here:

https://github.com/nemomobile-ux/nemo-packaging/blob/master/python-otherside/PKGBUILD

The build log is attached
[142-python-otherside.FAIL.log](https://github.com/thp/pyotherside/files/13504190/142-python-otherside.FAIL.log)

**Comment by thp** [comment]
Trying on Ubuntu 23.10 (mantic):

```
% gcc --version
gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

With these Qt 6 packages:

```
% dpkg -l 'qt6*dev'
...
ii  qt6-base-dev:amd64        6.4.2+dfsg-18  amd64        Qt 6 base development files
ii  qt6-declarative-dev:amd64 6.4.2+dfsg-3   amd64        Qt 6 declarative development files
ii  qt6-svg-dev:amd64         6.4.2-4ubuntu1 amd64        Qt 6 SVG - development files
```

And these Python 3 packages:

```
% dpkg -l 'python3*dev'
...
ii  python3-all-dev   3.11.4-5     amd64        package depending on all supported Python 3 development packages
ii  python3-dev       3.11.4-5     amd64        header files and a static library for Python (default)
ii  python3.11-dev    3.11.6-3     amd64        Header files and a static library for Python (v3.11)
```

The build seems to work and unit tests go through. Which version of Qt 6 / Python 3 are you using?

**Comment by jmlich** [comment]
```
$ qmake6 --version
QMake version 3.1
Using Qt version 6.6.0 in /usr/lib
```

```
jmlich@manjaro:~$ python --version
Python 3.11.6
```

```
jmlich@manjaro:~$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	23.1.0
Codename:	Vulcan
```

**Comment by thp** [comment]
@jmlich I think I fixed this in the latest commit (not part of a release yet). Please check if this fixes your build error.

It seems like Qt 6.5 and 6.6 are affected, because they [changed the type of `Q_RETURN_ARG()`](https://bugreports.qt.io/browse/QTBUG-113147
) without accounting for source compatibility of the [deprecated `QMetaMethod::invoke()` function](https://doc.qt.io/qt-6/qmetamethod-obsolete.html#invoke).

The fix creates a `QGenericReturnArgument()` "by hand" for use with the deprecated `QMetaMethod::invoke()` on Qt 6.5 and newer, and uses `Q_RETURN_ARG()` on older versions (like before).

**Comment by jmlich** [comment]
I can confirm, that it works now for me. Thanks.

**Comment by jmlich** [comment]
I have already added it as patch so tagged version is not needed.
