### ISSUE TITLE
SQLite3 support in the Android build

### ISSUE THREAD

**Issue by thp** [thp/pyotherside#40]
Following up from the discussion with @M4rtinK in https://github.com/gpodder/gpodder-android/commit/c0e7ec4bc61c274d061f500eda0217e1304eb7a9:

--
That Python 3 Android port is missing Sqlite in the build for some reason, so I'm afraid this won't work. :)

I'll eventually also need Sqlite for modRana, so I've tried to modify the Python build a bit like this:
http://paste.fedoraproject.org/190083/82680614

But it still lacked Sqlite afterwards (but the changes at least succeeded in adding CSV support).

**Comment by thp** [comment]
WIP (untested): https://github.com/thp/python3-android/commit/31434bef8771438f38106f92f8da21f78b2bd348

**Comment by M4rtinK** [comment]
Seems to be working, thanks a lot! I've rebuilt Python 3 & PyOtherSide and I can now successfully import & use sqlite in modRana ! :)

BTW, I had to add -lsqlite3 to the python.pri used to build pyotherside:
QMAKE_LIBS += -L/home/user/build/python3-android/build/9d-14-arm-linux-androideabi-4.8/lib -lpython3.3m -ldl -lm -lc -lssl -lcrypto -lsqlite3

Otherwise PyOtherSide would fail to build with some sqlite related errors. I have created a pull requests for the change:
https://github.com/thp/python3-android/pull/1

BTW, I wonder if the pri files & the absolute paths could be somehow handled in a better way, so that users don't have to copy the pri file from the Python build and to manually change the absolute path inside it. Maybe PyOtherSide could have a android pri file variant with relative path to the Python build in it ? If that worked, users would just have to make sure to clone Python and PyOtherSide  to the same folder.

**Comment by thp** [comment]
Maybe python3-android could provide a `python-config`-like dummy script:

https://github.com/thp/pyotherside-blackberry-dependencies

(files `python-config-bb10` and `python-config.sh`, for Android could be a single file)

Then, pyotherside doesn't need any `.pri` hacks, but just do it like that:

```
qmake PYTHON_CONFIG=../python3-android/python-config-android
```

**Comment by thp** [comment]
Closing. Rest of the tasks split off as #42.
